### ISSUE TITLE
Add auto refresh at DNS ttl

### ISSUE THREAD

**Issue by rdadoune** [eduardbcom/lookup-dns-cache#2]
It'd be nice if there was a way to auto refresh the dns cache for a given host when the TTL expires, or if not that, a way to retrieve the expire time for a given host. What are your thoughts?

**Comment by eduardbcom** [comment]
If at least one field within cache has been expired, the new resolve request would be emitted and the entire cache would be automatically updated.

https://github.com/eduardbcom/lookup-dns-cache/blob/35ad4c8953ea5b5ec3139fb3e303431a92f7d691/src/AddressCache.js#L14

https://github.com/eduardbcom/lookup-dns-cache/blob/master/src/Lookup.js#L178

Hope, I right understand your suggestion.

**Comment by eduardbcom** [comment]
Feel free to reopen.
