### ISSUE TITLE
Usage with `request` module

### ISSUE THREAD

**Issue by fabiob** [eduardbcom/lookup-dns-cache#3]
The `README` states that one can use this package along with the `request` module, by using a configuration option named `lookup`.

However, I digged into request/request sourcecode and could not find any reference of this property.

Is the `README` correct? If so, how does it work?

**Comment by eduardbcom** [comment]
https://github.com/nodejs/node/blob/master/lib/net.js#L1050

Feel free to ask any additional questions.

**Comment by ali-naman** [comment]
I get this error when I use request method

```
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: addresses must be a not empty array.
    at ResolveTask._resolved (/home/node/01/node_modules/lookup-dns-cache/src/ResolveTask.js:80:13)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:240:10)
```

**Comment by eduardbcom** [comment]
@ali-naman Can you provide a reproducible snippet of code ? Thx.

**Comment by ali-naman** [comment]
node version : v8.11.3

`const request = require('request');
cheerio = require('cheerio');
const {lookup} = require('lookup-dns-cache');


var scrapeURL = function(url){

	var options = {

		url : url,
		"rejectUnauthorized": false, 
		headers: {
		  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
		  rejectUnauthorized: false,
		  'User-Agent' : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36"
		},
	    lookup: lookup,

	};


	request(options, function (error, response, html){

		

		if(error || response.statusCode !== 200){
		  console.log(error);
		}


		var $ = cheerio.load(html);
		var title = $("title").text().toLowerCase().trim();

		console.log(title);


	});

}

//does not work for this url
var url = "http://www.elcorteingles.es/electronica/A23206971-camara-reflex-digital-canon-eos-1300d-con-objetivos-18-55-mm--50-mm-cube-kit/";

//works for this url
// var url = "https://github.com/";

scrapeURL(url)

`

**Comment by ali-naman** [comment]
It works for some urls like https://github.com/
but does not work for some others like http://www.elcorteingles.es/

node version: v8.11.3

```
const request = require('request');
cheerio = require('cheerio');
const {lookup} = require('lookup-dns-cache');


var scrapeURL = function(url){

	var options = {

		url : url,
		"rejectUnauthorized": false, 
		headers: {
		  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
		  rejectUnauthorized: false,
		  'User-Agent' : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36"
		},
	    lookup: lookup,

	};


	request(options, function (error, response, html){

		

		if(error || response.statusCode !== 200){
		  console.log(error);
		}


		var $ = cheerio.load(html);
		var title = $("title").text().toLowerCase().trim();

		console.log(title);


	});



}

//does not work for this url
var url = "http://www.elcorteingles.es/";

//works for this url
// var url = "https://github.com/";

scrapeURL(url)
```

**Comment by ali-naman** [comment]
It works for some urls like https://https://github.com/
but does not work for others like https://www.elcorteingles.es/

node version: v8.11.3

```
const request = require('request');
cheerio = require('cheerio');
const {lookup} = require('lookup-dns-cache');


var scrapeURL = function(url){

	var options = {

		url : url,
		"rejectUnauthorized": false, 
		headers: {
		  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
		  rejectUnauthorized: false,
		  'User-Agent' : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36"
		},
	    lookup: lookup,

	};


	request(options, function (error, response, html){

		

		if(error || response.statusCode !== 200){
		  console.log(error);
		}


		var $ = cheerio.load(html);
		var title = $("title").text().toLowerCase().trim();

		console.log(title);


	});



}

//does not work for this url
var url = "https://www.elcorteingles.es/";

//works for this url
var url = "https://github.com/";

scrapeURL(url)

```

**Comment by eduardbme** [comment]
The core reproducible code is
```js
dns.resolve6('www.elcorteingles.es', { ttl: true }, console.log)
> null []
```

So the result may be empty array.

Have fixed in https://github.com/eduardbcom/lookup-dns-cache/tree/2.1.0.

Thanks for your contribution.
